# Generated by Django 4.2.6 on 2023-10-22 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cadastro_produtos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fornecedor",
            name="endereco",
        ),
        migrations.RemoveField(
            model_name="fornecedor",
            name="telefones",
        ),
        migrations.AlterField(
            model_name="produto",
            name="descricao",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="produto",
            name="nome",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name="Telefone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telefone", models.CharField(max_length=20)),
                (
                    "fonecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telefones",
                        to="cadastro_produtos.fornecedor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rua", models.CharField(max_length=200)),
                ("bairro", models.CharField(max_length=200)),
                ("numero", models.IntegerField()),
                ("cidade", models.CharField(max_length=200)),
                (
                    "fornececedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enderecos",
                        to="cadastro_produtos.fornecedor",
                    ),
                ),
            ],
        ),
    ]
